import assert from 'node:assert/strict';
import {createRequire} from 'node:module';

const require = createRequire(import.meta.url);
const {chromium} = require(process.env.TRACEFIX_PLAYWRIGHT_MODULE || 'playwright');
const browser = await chromium.launch({headless: true});
try {
  const page = await browser.newPage({viewport: {width: 1440, height: 1000}});
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto((process.env.TRACEFIX_VERIFY_URL || 'http://127.0.0.1:3099') + '/#knowledge');
  const title = `浏览器验收：刷新状态回归 ${Date.now()}`;
  await page.getByRole('button', {name: '＋ 新建文档'}).click();
  await page.getByLabel('文档标题').fill(title);
  await page.getByLabel('文档内容').fill('## 测试步骤\n修改状态后重新加载页面，确认 PATCH 请求成功，验证刷新后状态保留。');
  await page.getByLabel('标签（英文逗号分隔）').fill('React,持久化');
  await page.getByRole('button', {name: '保存文档', exact: true}).click();
  await page.getByRole('status').filter({hasText: '已保存 v1'}).waitFor();
  await page.getByLabel('检索测试问题').fill(title);
  await page.getByRole('button', {name: '检索', exact: true}).click();
  await page.locator('.search-results article').first().waitFor();
  await page.getByLabel('文档内容').fill('## 测试步骤\n修复后应同时验证 PATCH 响应和全新页面加载后的完成状态。');
  await page.getByRole('button', {name: '保存文档', exact: true}).click();
  await page.getByRole('status').filter({hasText: '已保存 v2'}).waitFor();
  await page.screenshot({path: '.tracefix/console-knowledge.png', fullPage: true});
  await page.reload();
  await page.locator('.document-card').filter({hasText: title}).click();
  assert.match(await page.getByLabel('文档内容').inputValue(), /全新页面/);
  await page.getByLabel('允许 Agent 检索此文档').uncheck();
  await page.getByRole('button', {name: '保存文档', exact: true}).click();
  await page.getByRole('status').filter({hasText: '已保存 v3'}).waitFor();
  await page.getByLabel('检索测试问题').fill(title);
  await page.getByRole('button', {name: '检索', exact: true}).click();
  await page.waitForResponse(response => response.url().endsWith('/api/knowledge/search'));
  assert.equal(await page.locator('.search-results article').filter({hasText: title}).count(), 0);
  await page.locator('input[type=file]').setInputFiles({name: '上传验证.md', mimeType: 'text/markdown', buffer: Buffer.from('# 上传的回归方法\n使用浏览器 reload 检查状态。')});
  await page.getByRole('button', {name: '保存文档', exact: true}).click();
  await page.getByRole('status').filter({hasText: '已保存 v1'}).waitFor();
  await page.getByRole('navigation').getByRole('link', {name: /项目空间/}).click();
  await page.getByRole('heading', {name: /的运行配置/}).waitFor();
  await page.getByRole('button', {name: '查看项目运行'}).click();
  await page.getByRole('heading', {name: /Agent Runs/}).waitFor();
  assert.equal(await page.getByLabel('Agent 对话面板').count(), 1);
  await page.getByLabel('新的运行目标', {exact: true}).fill('浏览器验收：验证失败启动记录 ' + title);
  await page.getByRole('button', {name: '启动 Run ↑'}).click();
  await page.locator('.run-row').filter({hasText: title}).click();
  await page.locator('.log-view').filter({hasText: 'TRACEFIX_DATABASE_URL'}).waitFor();
  await page.getByRole('button', {name: '沉淀为知识'}).click();
  await page.getByRole('heading', {name: /新建文档/}).waitFor();
  assert.match(await page.getByLabel('文档内容').inputValue(), /来源/);
  await page.getByRole('button', {name: '保存文档', exact: true}).click();
  await page.getByRole('status').filter({hasText: '已保存 v1'}).waitFor();
  await page.setViewportSize({width: 390, height: 844});
  await page.screenshot({path: '.tracefix/console-mobile.png', fullPage: true});
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth));
  assert.deepEqual(errors, []);
  console.log('通过：导航、上传、编辑、刷新持久化、检索、停用、失败启动、运行记录转知识、移动端布局');
} finally {await browser.close();}
